//
// Generated file, do not edit! Created by nedtool 5.7 from message/TimeoutMSG.msg.
//

#ifndef __TIMEOUTMSG_M_H
#define __TIMEOUTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>message/TimeoutMSG.msg:17</tt> by nedtool.
 * <pre>
 * message TimeoutMSG
 * {
 *     int macAddress;
 * }
 * </pre>
 */
class TimeoutMSG : public ::omnetpp::cMessage
{
  protected:
    int macAddress;

  private:
    void copy(const TimeoutMSG& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TimeoutMSG&);

  public:
    TimeoutMSG(const char *name=nullptr, short kind=0);
    TimeoutMSG(const TimeoutMSG& other);
    virtual ~TimeoutMSG();
    TimeoutMSG& operator=(const TimeoutMSG& other);
    virtual TimeoutMSG *dup() const override {return new TimeoutMSG(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMacAddress() const;
    virtual void setMacAddress(int macAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimeoutMSG& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimeoutMSG& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TIMEOUTMSG_M_H

